package springContents;

import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;

/**
 * Standard main class for Spring, generated by Spring template
 */
@SpringBootApplication
public class Application {

    public static void main(String[] args) {
//        StatusController.setSystemInfoFacade(new ServerStatusTrueDetailsFacade()); //This is where it gets decided which implementation of the facade to use
        SpringApplication.run(Application.class, args);
    }
}